### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by khushi2305**
This is a basic layout of the Home page with a Menu bar . Menu Bar is designed as a separate class so that the same menu bar code can be reused by other pages . The code is compatible to different device orientations . Screenshots of the layout has given below .

Home page 
https://user-images.githubusercontent.com/59967262/83519306-5f3f0900-a4f9-11ea-949b-f36a25ff19a6.jpeg

Menu bar 
https://user-images.githubusercontent.com/59967262/83518941-be504e00-a4f8-11ea-8ba5-5eddf8891bef.jpeg

### CODE REVIEW

**Comment by oshhh** [comment]
@googlebot I fixed it

**Comment by khushi2305** [comment]
@googlebot I fixed it.

**Comment by oshhh** [comment]
Consider keeping meaningful names of the test files instead of widget_test.dart.

**Comment by khushi2305** [comment]
@googlebot I fixed it.

**Comment by sonianjali** [comment]
@googlebot I consent

**Comment by sonianjali** [comment]
@googlebot I consent

**Comment by anjalisoni3655** [comment]
@googlebot I consent

**Pull request closed without merging**
