### PR TITLE
created default flutter app

### PR DESCRIPTION
**Pull request by oshhh**
Set up default flutter application

TESTING: This is a verified starter code for flutter applications created by android studio.

### CODE REVIEW

**Comment by akashagarwal** [comment]
Please remove all boilerplate comments and test from the files in this pull request. 
Also does the PNG files need to be a part of the codebase ? 
Maybe look at other flutter apps on this.

**Comment by oshhh** [comment]
I can do that in this branch itself but that would make the code review tougher as then the code would include my own changes as well. Currently this branch has no changes done by me only default app creation by android studio. Proper setup was to be done in a separate PR as discussed with @dreamplay .

**Comment by oshhh** [comment]
@akashagarwal this default app is also required to check if the travis integration is working properly since this app also contains tests.

**Comment by akashagarwal** [comment]
what about the PNG files and other binaries ?
Do you need to check them in ?

**Comment by oshhh** [comment]
@akashagarwal Those PNGs are in the android folder as app icon. I'm not sure if I should delete them, and what will happen to the app icon of the app. Maybe we can later substitute them with our own app icon.

**Comment by dreamplay** [comment]
I agree with @akashagarwal on removing boiler plate comments/texts.
Don't add any changes in this PR but text changes is fine.

**Comment by oshhh** [comment]
@akashagarwal @dreamplay Okay, I'll remove the comments. I hope it won't impact the branches based on this branch.

**Comment by akashagarwal** [comment]
> @akashagarwal Those PNGs are in the android folder as app icon. I'm not sure if I should delete them, and what will happen to the app icon of the app. Maybe we can later substitute them with our own app icon.

@oshhh : I know that we need the images. But do they need to be part of the codebase  ? Please check how other flutter apps do it.

**Comment by oshhh** [comment]
I think those

> > @akashagarwal Those PNGs are in the android folder as app icon. I'm not sure if I should delete them, and what will happen to the app icon of the app. Maybe we can later substitute them with our own app icon.
> 
> @oshhh : I know that we need the images. But do they need to be part of the codebase ? Please check how other flutter apps do it.

@akashagarwal  I'll put it in .gitignore then

**Comment by akashagarwal** [comment]
> > > @akashagarwal Those PNGs are in the android folder as app icon. I'm not sure if I should delete them, and what will happen to the app icon of the app. Maybe we can later substitute them with our own app icon.
> > 
> > 
> > @oshhh : I know that we need the images. But do they need to be part of the codebase ? Please check how other flutter apps do it.
> 
> @akashagarwal I'll put it in .gitignore then

Where are you keeping them ? Did you check how other flutter apps handle them ?

**Comment by oshhh** [comment]
@akashagarwal keeping them locally. All the flutter apps I saw on github have it in their code itself. Not sure how its done professionally.

**Comment by dreamplay** [comment]
> @akashagarwal keeping them locally. All the flutter apps I saw on github have it in their code itself. Not sure how its done professionally.

I think what akash meant was instead of having the files bundled in your source code, can we have only their urls and then they can be fetched by the app in run time.
This'd help make the bundle size of our app much smaller.

I'm okay with having them checked in for now if that's by default, maybe add a TODO to replace image/video/static files via a url so that bundle only consists of our code.

**Comment by oshhh** [comment]
okay, I'll add them back

**Comment by dreamplay** [comment]
Squash and Merge please.

**Pull request merged**
