### PR TITLE
added snackbars to display the error messages 

### PR DESCRIPTION
**Pull request by anjalisoni3655**
Snackbar is implemented to show the error for the following cases:
1. for login failed.
2. for logout failed.
3. for no offers selected.
4. for no devices access.
5. no homes selected.
tested manually by running on the local device.

### CODE REVIEW

**Comment by anjalisoni3655** [comment]
@googlebot I consent.

**Comment by dreamplay** [comment]
please add details about TESTING to description -- what was done, manual testing for each case, unit tests, or integration tests??

**Comment by anjalisoni3655** [comment]
@googlebot I consent.

**Comment by anjalisoni3655** [comment]
> please add details about TESTING to description -- what was done, manual testing for each case, unit tests, or integration tests??

For now, only manual testing has been done.

**Pull request merged**
